import Head from "next/head";
import { useEffect } from "react";
// import { Fragment, useEffect } from "react";
import styles from "../styles/Home.module.css";
// import { fetchRestaurants } from "./api/restaurants";
// import { GetServerSideProps } from 'next'


const Home = ({}) => {
 /*  if (error) {
    return <div>An error occured: {error.message}</div>;
  } */
useEffect(async ()=>{
  const resp= await fetch('http://localhost:1337/api/restaurants')
const data= await resp.json()
console.log("data",data)
},[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    {/*   {restaurants.map((restaurant) => (
        <Fragment key={restaurant.id}>
          <p>{restaurant.attributes.name}</p>
          <p>{restaurant.attributes.description}</p>
        </Fragment>
      ))} */}
    </div>
  );
};

/* export const getServerSideProps: GetServerSideProps = async (_ctx: any) => {
  // ...
} */
/* Home.getInitialProps = async (_ctx: any) => {
  try {
    const d = await fetchRestaurants('/categories');
    console.log("data in index---", d);
    return { restaurants: d };
  } catch (error) {
    return { error };
  }
}; */

export default Home;
