import Head from "next/head";
import { Fragment } from "react";
import styles from "../styles/Home.module.css";
import { fetchRestaurants } from "./api/restaurants";

const Home = ({ restaurants, error }) => {
  if (error) {
    return <div>An error occured: {error.message}</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {restaurants.map((restaurant) => (
        <Fragment key={restaurant.id}>
          <p>{restaurant.attributes.name}</p>
          <p>{restaurant.attributes.description}</p>
        </Fragment>
      ))}
    </div>
  );
};

Home.getInitialProps = async (_ctx: any) => {
  try {
    const d = await fetchRestaurants('/restaurants');
    console.log("data in index---", d);
    return { restaurants: d };
  } catch (error) {
    return { error };
  }
};

export default Home;
